/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      colors: {
        primary: '#091426',
        'on-primary': '#ffffff',
        'primary-container': '#1e293b',
        'on-primary-container': '#8590a6',
        'primary-fixed': '#d8e3fb',
        'primary-fixed-dim': '#bcc7de',
        'on-primary-fixed': '#111c2d',
        'on-primary-fixed-variant': '#3c475a',
        'inverse-primary': '#bcc7de',

        secondary: '#006c49',
        'on-secondary': '#ffffff',
        'secondary-container': '#6cf8bb',
        'on-secondary-container': '#00714d',
        'secondary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',

        tertiary: '#330009',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#590016',
        'on-tertiary-container': '#ff4e69',
        'tertiary-fixed': '#ffdadb',
        'tertiary-fixed-dim': '#ffb2b7',
        'on-tertiary-fixed': '#40000d',
        'on-tertiary-fixed-variant': '#92002a',

        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',

        surface: '#f6fafe',
        'surface-dim': '#d6dade',
        'surface-bright': '#f6fafe',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f4f8',
        'surface-container': '#eaeef2',
        'surface-container-high': '#e4e9ed',
        'surface-container-highest': '#dfe3e7',
        'on-surface': '#171c1f',
        'on-surface-variant': '#45474c',
        'inverse-surface': '#2c3134',
        'inverse-on-surface': '#edf1f5',

        outline: '#75777d',
        'outline-variant': '#c5c6cd',
        'surface-tint': '#545f73',
        'surface-variant': '#dfe3e7',
        background: '#f6fafe',
        'on-background': '#171c1f',
      },
      spacing: {
        'sidebar': '256px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'container-padding': '24px',
        'gutter': '16px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
    },
  },
  plugins: [],
}
